import { GENERATED_REGISTRY_FILE, loadSketchSources, writeFileWithBanner } from "./lib";
import { pathToFileURL } from "node:url";

function buildRegistrySource(): string {
  const sources = loadSketchSources();

  const imports = sources
    .map(
      ({ manifest }) =>
        `import ${manifest.className} from "@/sketches/${manifest.slug}/${manifest.className}";`,
    )
    .join("\n");

  const manifestLines = sources
    .map(({ manifest }, index) => {
      const serialized = JSON.stringify(manifest, null, 2)
        .split("\n")
        .map((line) => `  ${line}`)
        .join("\n");
      return `const manifest${index + 1}: SketchManifest =\n${serialized};`;
    })
    .join("\n\n");

  const entries = sources
    .map(
      ({ manifest }, index) =>
        `  { manifest: manifest${index + 1}, Sketch: ${manifest.className} },`,
    )
    .join("\n");

  return `// Auto-generated by scripts/sync-sketches.ts. Do not edit by hand.

import type { SketchManifest } from "@/lib/sketch-core/manifestSchema";
import type { PlotterSketch } from "@/lib/sketch-core/PlotterSketch";
${imports}

export type SketchConstructor = new () => PlotterSketch;

export interface SketchRegistryEntry {
  manifest: SketchManifest;
  Sketch: SketchConstructor;
}

${manifestLines}

export const sketchRegistry: SketchRegistryEntry[] = [
${entries}
];

export const sketchRegistryBySlug = Object.fromEntries(
  sketchRegistry.map((entry) => [entry.manifest.slug, entry]),
) as Record<string, SketchRegistryEntry>;
`;
}

export function syncSketchRegistry(): void {
  const source = buildRegistrySource();
  writeFileWithBanner(GENERATED_REGISTRY_FILE, source);
}

const isDirectExecution =
  process.argv[1] !== undefined &&
  import.meta.url === pathToFileURL(process.argv[1]).href;

if (isDirectExecution) {
  syncSketchRegistry();
  console.log(`Synced sketch registry: ${GENERATED_REGISTRY_FILE}`);
}
